# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build_and_tests:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |        
        pytest
    - name: Build wheel file
      run: |
        python3 -m build
    - name: Checking wheel file
      run: |
        check-wheel-contents ./dist
    - name: Run
      run: |
        pip install dist/Codac-0.9.0-py3-none-any.whl
        Codac        
    - name: Archive wheel file
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: |
          dist          
    - name: Archive client_data
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: |          
          client_data
    - name: Archive logs
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: |          
          logs